import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import React, { useState } from 'react';
import Link from 'next/link';
// import UserModel from '../nobox/record-structures/user';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>iostream by Orunto and Olusola</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <nav className={styles.nav}>
          <header> Dashboard</header>
        </nav>

        <aside>
          <header>iostream</header>

          <div>
            <Link href="#">Dashboard</Link>
            <Link href="#">Support</Link>
            <Link href="#">Settings</Link>
          </div>
        </aside>

        <section>
          <h1> Nothing to see here for now</h1>
        </section>
      </main>
    </>
  )
}
